version: "3.9"

networks:
  app-network:

services:
  receiver:
    build: ./receiver
    container_name: receiver
    hostname: receiver
    networks:
      - app-network
    ports:
      - 3002:3002
    environment:
      - PORT=3002
  sender:
    build: ./sender
    container_name: sender
    hostname: sender
    networks:
      - app-network
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - RECEIVER=http://receiver:3002
